<?php

namespace EventBundle\Repository;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEvent($keyWord)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(array('p'))
            ->from('EventBundle:Event', 'p')
            ->where('p.libelle LIKE :motClee')
            ->orWhere('p.description LIKE :motClee')
            ->orderBy('p.date', 'DESC')
            ->setParameter('motClee', '%'.$keyWord.'%')
            ->getQuery();
        return $q->getResult();
    }
}
